name: flutter_weather_app
description: A weather app for android built using flutter
version: 0.2.0

environment: 
  sdk: ">=3.7.0"

dependencies: 
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^1.4.0

flutter:
 uses-material-design: true
 assets:
  - .env
