name: flutter_weather_app
description: A weather app for android built using flutter
version: 0.0.0

environment: 
  sdk: ">=3.7.0"

dependencies: 
  flutter:
    sdk: flutter

flutter:
 uses-material-design: true